package config

import (
	"os"
	"path/filepath"
	"testing"
)

func TestConfigRoundtrip(t *testing.T) {
	// The tests will run in a temporary directory generated by go test,
	// so writing to the config path should be safe.
	err := ClearConfig()
	if err != nil && !os.IsNotExist(err) {
		t.Logf("ClearConfig failed, but continuing: %v", err)
	}

	cfg := Config{
		Language:       "zh",
		TelegramToken:  "dummy_token",
		WorkspacePath:  "/tmp/workspace",
		TTSVoice:       "zh-CN-YunyangNeural",
		AllowedChatIDs: []string{"123", "456"},
		Theme:          "dark",
	}

	err = SetConfig(cfg)
	if err != nil {
		t.Fatalf("Failed to SetConfig: %v", err)
	}

	if !Exists() {
		t.Errorf("Expected config to exist after SetConfig")
	}

	err = Load()
	if err != nil {
		t.Fatalf("Failed to Load config: %v", err)
	}

	loaded := GetConfig()
	if loaded.Language != "zh" {
		t.Errorf("Expected Language 'zh', got %q", loaded.Language)
	}
	if len(loaded.AllowedChatIDs) != 2 || loaded.AllowedChatIDs[0] != "123" {
		t.Errorf("Expected AllowedChatIDs [123, 456], got %v", loaded.AllowedChatIDs)
	}
	if loaded.Theme != "dark" {
		t.Errorf("Expected Theme 'dark', got %q", loaded.Theme)
	}

	err = ClearConfig()
	if err != nil {
		t.Fatalf("Failed to ClearConfig: %v", err)
	}

	if Exists() {
		t.Errorf("Expected config to not exist after ClearConfig")
	}
}

func TestGetConfigPath_IsWithinDataDir(t *testing.T) {
	path, err := getConfigPath()
	if err != nil {
		t.Fatalf("getConfigPath failed: %v", err)
	}
	if filepath.Base(filepath.Dir(path)) != "data" {
		t.Errorf("Expected config to be in 'data' directory, got: %s", path)
	}
}
