// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function ClearConfig():Promise<void>;

export function GetConfig():Promise<config.Config>;

export function HasConfig():Promise<boolean>;

export function IsBotRunning():Promise<boolean>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function StartBot():Promise<void>;

export function StopBot():Promise<void>;
