// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearConfig() {
  return window['go']['main']['App']['ClearConfig']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function HasConfig() {
  return window['go']['main']['App']['HasConfig']();
}

export function IsBotRunning() {
  return window['go']['main']['App']['IsBotRunning']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartBot() {
  return window['go']['main']['App']['StartBot']();
}

export function StopBot() {
  return window['go']['main']['App']['StopBot']();
}
